spring.application.name=identity-service

server.port=8181
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
