spring.application.name=identity-service

server.port=5151
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=K7mQ9xL2vR8nP4wT6yU1iO3pA5sD7fG9hJ2kL4zX6cV8bN1mQ3rT5yU7iO9pA2sD
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

#jwt.secret=${JWT_SECRET}
#jwt.access-token.expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
#jwt.refresh-token.expiration=${JWT_REFRESH_TOKEN_EXPIRATION}

