spring.application.name=flight-service

server.port=5153

spring.datasource.url=${FLIGHT_DB_URL}
spring.datasource.username=${FLIGHT_DB_USERNAME}
spring.datasource.password=${FLIGHT_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

duffel.api.base-url=https://api.duffel.com
duffel.api.key=${DUFFEL_API_KEY}
duffel.api.version=${DUFFEl_API_VERSION}

eureka.client.service-url.defaultZone= http://localhost:8761/eureka/

management.endpoints.web.exposure.include= health,info